### ISSUE TITLE
Twitter og tags Problem

### ISSUE THREAD

**Issue by cagdasc** [Priyansh-Kedia/OpenGraphParser#12]
Hi,

First of all thank you for this useful library. But I couldn't get `og` tags for Twitter. I think this is`Jsoup` problem. Do you know anything about this?

**Comment by pknotfound** [comment]
Hello @cagdasc 
Can you please share some links you were not able to use?
I will check them out soon

**Comment by cagdasc** [comment]
@Priyansh-Kedia there is no specific url. I tried it for many different tweets URL.

**Comment by pknotfound** [comment]
Ahh okay, I will check it out soon.

Thank you for reporting this

**Comment by pknotfound** [comment]
Hello @cagdasc 
I found this issue, and have made some fixes and pushed those to a branch named _og_tags_bug_.

I have done some testing.
Can you also make sure if it fixes the issue now?

**Comment by cagdasc** [comment]
@Priyansh-Kedia I will try. Thank you 👍

**Comment by pknotfound** [comment]
@cagdasc 
Did you test it out for your case?

**Comment by cagdasc** [comment]
@Priyansh-Kedia it works well. I am waiting next version. Thank you 👍🏻

**Comment by pknotfound** [comment]
That's great.
Thanks for reporting the issue.
