### ISSUE TITLE
[BUG] Getting crash while parsing url on release builds (with minifyEnabled = true).

### ISSUE THREAD

**Issue by ashishcors** [Priyansh-Kedia/OpenGraphParser#19]
Was unable to pull logs due to it being minified release build.

**Comment by pknotfound** [comment]
Hello @jasperx21 
Thank you for reporting the bug
Can you please provide the link(s) which were leading to a crash on parsing?

Thanks

**Comment by ashishcors** [comment]
all links were crashing for me, try anything.
This was the exception: https://stackoverflow.com/questions/40703857/android-jsoup-exceptionininitializererror

**Comment by pknotfound** [comment]
Okay, I will test this out and review your PR too.

Thank you

**Comment by pknotfound** [comment]
@jasperx21 Can you also please link this issue to the PR you created.

**Comment by ashishcors** [comment]
I don't see any option to link these. Can you try?

**Comment by pknotfound** [comment]
[Closed] See #18
