### ISSUE TITLE
Allow specifying a Proxy for the HTTP connection

### ISSUE THREAD

**Issue by singpolyma** [Priyansh-Kedia/OpenGraphParser#22]
**Is your feature request related to a problem? Please describe.**
My app needs to be able to fetch OG tags over Tor.

**Describe the solution you'd like**
Ability to specify a `Proxy` when parsing from URL.

**Describe alternatives you've considered**
And/or would also be nice to be able to parse from a String of a URL fetched some other way.

**Comment by pknotfound** [comment]
Thanks @singpolyma 
Can you explain what you mean by the alternative you have mentioned?

**Comment by singpolyma** [comment]
If I could do the http fetch with my existing http client and feed it to the OpenGraphParser as a `String` or `File` then it wouldn't matter how the http fetcher worked.

**Comment by pknotfound** [comment]
Do you mean using the parser just to get meta tags from the `String`, and not fetch the content by itself?

**Comment by singpolyma** [comment]
right.  I don't prefer that option necessarily, but it might be a good option to have for other reasons, and it would happen to work here since I of course have an http client in my app already.

**Comment by pknotfound** [comment]
Yes definitely a good idea, I would create another issue for the new change

Thanks

**Comment by pknotfound** [comment]
> Yes definitely a good idea, I would create another issue for the new change
> 
> Thanks

Ref:- #26

**Comment by pknotfound** [comment]
New update : 2.5.6
