### ISSUE TITLE
Set maxBodySize to something sane

### ISSUE THREAD

**Issue by singpolyma** [Priyansh-Kedia/OpenGraphParser#23]
**Is your feature request related to a problem? Please describe.**
A server can stream a giant or even infinite amount of data, and I don't want to download it all just to get the OG tags which are supposed to be near the top.

**Describe the solution you'd like**
Use `maxBodySize` of 4k or similar.

**Comment by pknotfound** [comment]
Thanks @singpolyma 
Will add the option and update accordingly
