### ISSUE TITLE
Lower timeout

### ISSUE THREAD

**Issue by singpolyma** [Priyansh-Kedia/OpenGraphParser#24]
**Is your feature request related to a problem? Please describe.**
Currently timeout is 100 seconds which feels like forever to users possibly waiting for an action.

**Describe the solution you'd like**
User a lower timeout.

**Describe alternatives you've considered**
Allow library users to specify timeout.

**Comment by pknotfound** [comment]
Hello @singpolyma
Thanks for your suggestions (#23 , #22)

This seems a valid proposition. I will update the library with the new changes when possible.
