### ISSUE TITLE
Some urls don't work.

### ISSUE THREAD

**Issue by June6-android** [Priyansh-Kedia/OpenGraphParser#8]
This library is working quite good in many cases. It's snappy and doesn't seem to consume many resources. It works good on recyclerviews as well.

But, some urls, even popular ones such as www.google.com does not work. The return results are all 'null' and the error logs  says that 

'Unable to resolve host "xn--()-3y0jv63bvsjymf": No address associated with hostname'

Is there a workaround for this?

**Comment by pknotfound** [comment]
Hello @June6-android 
Thanks for the observation

Some URLs do not follow the protocol, and the response that you get can be due to the referrer or the agent that is used in the OpenGraphProtocol.

This will be looked into shortly, meanwhile, any contribution from your side is also welcome.

**Comment by pknotfound** [comment]
Also, it would be great if you can list some of the popular URLs you mentioned above here too.
@June6-android
