### ISSUE TITLE
Is the null check normal?

### ISSUE THREAD

**Issue by mazeloper** [Priyansh-Kedia/OpenGraphParser#9]
First of all, I'm not good at English, so please forgive me.

When checking for title and description null, is there any reason to use openGraphResult!!.title.equals("null") ? It's actually null, but it's not a string, so it's not a normal null check.

library : openGraphResult!!.title?.isEmpty() == true || openGraphResult!!.title.equals("null")

I think this is it
openGraphResult!!.title?.isNullOrEmpty() == true || openGraphResult!!.title.equals("null")

It's always in good use. please check.

Thank you 😀

**Comment by pknotfound** [comment]
@sta-con can you link this issue to the PR you created?

**Comment by mazeloper** [comment]
@Priyansh-Kedia  
Sorry. I'm not sure what you mean

I'm not very good at using Git 🙏
